import type { Mission } from './campaign';
import type { LocalizedText } from '../data/professional/types';

const localized = (es: string, en: string): LocalizedText => ({ es, en });
// Each rejected option explains its own outcome, without revealing the accepted answer.
const failures: Record<string, [LocalizedText, LocalizedText]> = {
  responsive: [localized('El contenido queda recortado y parte del formulario sigue inaccesible.', 'Content is clipped and part of the form remains inaccessible.'), localized('El texto pierde legibilidad y la columna sigue siendo demasiado ancha.', 'Text becomes unreadable and the column is still too wide.')],
  'layout-a11y': [localized('El elemento sigue sin ofrecer interacción de teclado ni comunicar su estado.', 'The element still offers no keyboard interaction or state information.'), localized('Quien usa teclado sigue sin poder abrir el menú.', 'Keyboard users still cannot open the menu.')],
  'client-handoff': [localized('El alcance crece sin ajustar el plazo: la entrega queda comprometida.', 'Scope grows without a deadline adjustment, putting delivery at risk.'), localized('El cliente no sabe qué incluye la entrega y no puede validarla.', 'The client does not know what delivery includes and cannot validate it.')],
  'xul-learn': [localized('La reescritura elimina comportamiento que todavía no has identificado.', 'The rewrite removes behavior you have not yet identified.'), localized('Aunque compile, no sabes qué cambio corrige el fallo ni qué ha roto.', 'Even if it builds, you cannot tell which change fixes the bug or what broke.')],
  'xul-lifecycle': [localized('La referencia apunta a una pantalla destruida y no restaura la nueva.', 'The reference points to a destroyed screen and does not restore the new one.'), localized('Bloquear el giro oculta el síntoma; al recrear la pantalla se pierde la selección.', 'Locking rotation hides the symptom; recreating the screen still loses the selection.')],
  'xul-review': [localized('La captura no permite repetir el caso ni verificar la corrección.', 'The screenshot cannot reproduce the case or verify the fix.'), localized('Una ejecución aislada no comprueba que el fallo haya desaparecido.', 'One isolated run does not verify that the failure is gone.')],
  'signlab-coordinates': [localized('El ajuste manual solo coincide en una escala y vuelve a fallar al redimensionar.', 'The manual adjustment only matches one scale and fails again when resized.'), localized('Cambiar solo el tamaño de las zonas deja sus posiciones desalineadas.', 'Changing only region sizes leaves their positions misaligned.')],
  'signlab-overlap': [localized('El retraso no decide qué región gana: ambas acciones siguen siendo posibles.', 'The delay does not decide which region wins: both actions remain possible.'), localized('Evitas la duplicidad, pero dejas al visitante sin interacción.', 'You avoid duplicate actions but leave visitors with no interaction.')],
  'signlab-delivery': [localized('La prueba no detecta errores en los bordes ni al cambiar de escala.', 'The test misses boundary and scaling errors.'), localized('La instalación no verifica que los gestos activen la región correcta.', 'Installation does not verify that gestures activate the correct region.')],
  'school-permissions': [localized('Abres permisos innecesarios sin identificar el acceso que falta.', 'You grant unnecessary permissions without identifying the missing access.'), localized('Eliminar la contraseña expone el servidor y no corrige los permisos de la carpeta.', 'Removing the password exposes the server and does not fix folder permissions.')],
  'school-backup': [localized('El reinicio interrumpe las clases sin dar tiempo a guardar el trabajo.', 'The reboot interrupts lessons without time to save work.'), localized('Pierdes registros útiles para diagnosticar un fallo de actualización.', 'You lose logs needed to diagnose an update failure.')],
  'school-inventory': [localized('El siguiente turno debe repetir el diagnóstico desde cero.', 'The next shift must repeat the diagnosis from scratch.'), localized('Expones credenciales sin documentar cómo se recuperó el servicio.', 'You expose credentials without documenting how service was restored.')],
  'alcatel-desk': [localized('La fibra sigue sin destino en el modelo aunque no se vea.', 'The fiber still has no destination in the model even if it is hidden.'), localized('El color no crea el extremo que falta; el diseño sigue inválido.', 'Color does not create the missing endpoint; the design remains invalid.')],
  'alcatel-statue': [localized('Asignas a todos los tramos la longitud máxima y sobreestimas el material.', 'You assign the maximum length to every segment and overestimate materials.'), localized('La media global mezcla materiales distintos y pierde sus cantidades reales.', 'The global average mixes different materials and loses their actual quantities.')],
  'alcatel-platform': [localized('Añades otra copia que también puede divergir cuando cambie la regla.', 'You add another copy that can also diverge when the rule changes.'), localized('El mismo diseño sigue produciendo resultados incompatibles.', 'The same design still produces incompatible results.')],
  'nokia-connectivity': [localized('El color compartido no demuestra que exista una conexión entre nodos.', 'A shared color does not prove that nodes are connected.'), localized('Centrar el plano no enlaza los extremos desconectados.', 'Centering the drawing does not link disconnected endpoints.')],
  'nokia-snake': [localized('Declarar conectividad no comprueba el recorrido de los paquetes.', 'Declaring connectivity does not verify the packet route.'), localized('Una ruta que se cruza no cumple los límites del tablero.', 'A route that crosses itself does not satisfy the board constraints.')],
  'nokia-geometry': [localized('Un único tramo horizontal deja sin comprobar tangencias y extremos.', 'One horizontal segment leaves tangencies and endpoints unchecked.'), localized('Redondear coordenadas altera la geometría que intentas validar.', 'Rounding coordinates changes the geometry you are trying to validate.')],
  'vector-report': [localized('La cabecera no comprueba si han cambiado los datos del informe.', 'The header does not verify whether report data changed.'), localized('Puedes producir antes un informe con totales incorrectos.', 'You may produce a report with incorrect totals faster.')],
  'vector-nlp': [localized('La evaluación reutiliza ejemplos aprendidos y sobreestima el resultado.', 'Evaluation reuses learned examples and overestimates performance.'), localized('Excluir casos difíciles sesga la evaluación frente al uso real.', 'Excluding difficult cases biases evaluation against real use.')],
  'vector-workflow': [localized('El flujo continúa consumiendo recursos por encima del límite.', 'The workflow keeps consuming resources above the limit.'), localized('El exceso sigue ocurriendo y el equipo pierde visibilidad para detenerlo.', 'The overrun continues and the team loses visibility needed to stop it.')],
  'anexia-requirements': [localized('El esquema no aclara quién puede entregar o recibir una llave.', 'The schema does not clarify who may hand over or receive a key.'), localized('La tabla fija supuestos que el cliente todavía no ha validado.', 'The table locks in assumptions the client has not validated.')],
  'anexia-mobile': [localized('Deshabilitar el botón no detiene una reentrega de red.', 'Disabling the button does not stop a network redelivery.'), localized('El retraso cambia cuándo llega el duplicado, pero no evita su efecto.', 'The delay changes when the duplicate arrives but does not prevent its effect.')],
  'anexia-valuation': [localized('La métrica de entrenamiento oculta el fallo sobre viviendas nuevas.', 'The training metric hides the failure on new homes.'), localized('Más decimales no mejoran la capacidad de predecir viviendas nuevas.', 'More decimal places do not improve predictions on new homes.')],
  'dag-tests': [localized('Al borrar pruebas dejas comportamientos sin verificar.', 'Deleting tests leaves behavior unverified.'), localized('Un resultado forzado oculta regresiones y deja de servir como comprobación.', 'A forced result hides regressions and no longer serves as a check.')],
  'dag-ai': [localized('El cambio excede el diagnóstico y aplica una hipótesis sin validar.', 'The change exceeds diagnosis and applies an unverified hypothesis.'), localized('El equipo toma decisiones con una certeza que la evidencia no demuestra.', 'The team makes decisions based on certainty the evidence does not support.')],
};
// These are fictional training cases. Career claims continue to come from the public model.
function quiz(id: string, target: string, title: LocalizedText, briefing: LocalizedText, options: LocalizedText[], correct: number, explanation: LocalizedText, seconds = 75): Mission {
  const mechanics: Record<string, Mission['mechanic']> = {
    responsive: 'bug', 'layout-a11y': 'bug', 'xul-lifecycle': 'bug',
    'signlab-coordinates': 'routing', 'signlab-overlap': 'bug', 'signlab-delivery': 'trace',
    'school-permissions': 'trace', 'alcatel-desk': 'bug', 'alcatel-statue': 'routing', 'alcatel-platform': 'architecture',
    'nokia-connectivity': 'trace', 'nokia-snake': 'routing', 'nokia-geometry': 'bug',
    'vector-report': 'trace', 'vector-nlp': 'trace', 'anexia-mobile': 'architecture', 'anexia-valuation': 'trace',
    'dag-tests': 'architecture', 'dag-ai': 'trace',
  };
  return { id, target, seconds, mechanic: mechanics[id] ?? 'priority', title, briefing, choices: options.map((label, i) => ({ id: `${id}-${i}`, label, accepted: i === correct, feedback: i === correct ? explanation : failures[id][i < correct ? i : i - 1] })) };
}

export const extraMissions: Mission[] = [
  quiz('responsive', 'terminal', localized('Maquetación contra reloj', 'Layout against the clock'), localized('El cliente revisa la web en un móvil de 360 px. La columna fija de 960 px desborda. ¿Qué cambio probarías?', 'The client reviews the site on a 360 px phone. A fixed 960 px column overflows. What would you test?'), [localized('Ocultar todo el desbordamiento', 'Hide all overflow'), localized('width: 100%; max-width: 960px y revisar el contenido', 'width: 100%; max-width: 960px and check the content'), localized('Reducir todo el texto a 8 px', 'Shrink all text to 8 px')], 1, localized('El contenedor se adapta. Comprueba también imágenes, espaciado y navegación en móvil.', 'The container adapts. Also check images, spacing and navigation on mobile.'), 45),
  quiz('layout-a11y', 'review', localized('La entrega también se usa con teclado', 'Delivery works with a keyboard too'), localized('El menú solo se abre al pasar el ratón. ¿Cómo permites acceder sin ratón?', 'The menu only opens on hover. How do you make it usable without a mouse?'), [localized('Botón real, foco visible y estado expandido', 'A real button, visible focus and expanded state'), localized('Un div con un icono más grande', 'A div with a larger icon'), localized('Explicar que hace falta un ratón', 'Explain that a mouse is required')], 0, localized('La interacción debe poder operarse con teclado y comunicar su estado.', 'The interaction must work with a keyboard and communicate its state.')),
  quiz('client-handoff', 'team', localized('Cerrar alcance, abrir la puerta', 'Close scope, open the door'), localized('La web está lista. Llega un «ya que estamos» con cinco páginas nuevas. ¿Cómo cierras la entrega?', 'The site is ready. A “while you are at it” request adds five pages. How do you close delivery?'), [localized('Añadirlo todo sin cambiar la fecha', 'Add everything without changing the date'), localized('Ignorar el mensaje', 'Ignore the message'), localized('Validar lo acordado y presupuestar la ampliación', 'Validate the agreed scope and estimate the extension')], 2, localized('Una entrega verificable y un alcance explícito protegen al cliente y al proyecto.', 'Verifiable delivery and explicit scope protect the client and the project.')),
  quiz('xul-learn', 'team', localized('Un componente por conocer', 'An unfamiliar component'), localized('Debes corregir un fallo en un componente Android que todavía no conoces. ¿Por dónde empiezas?', 'You must fix a failure in an Android component you do not yet know. Where do you start?'), [localized('Reescribirlo de memoria', 'Rewrite it from memory'), localized('Reproducir el caso y pedir una revisión guiada', 'Reproduce the case and ask for a guided review'), localized('Cambiar varias cosas hasta que compile', 'Change several things until it builds')], 1, localized('Un ejemplo mínimo y una revisión convierten la tarea en aprendizaje compartido.', 'A minimal example and a review turn the task into shared learning.')),
  quiz('xul-lifecycle', 'terminal', localized('El museo gira', 'The museum rotates'), localized('Al girar el móvil, la ficha seleccionada vuelve a la primera. ¿Qué hay que conservar?', 'Rotating the phone resets the selected exhibit to the first one. What should survive?'), [localized('La selección como estado restaurable', 'The selection as restorable state'), localized('Una referencia permanente a la pantalla destruida', 'A permanent reference to the destroyed screen'), localized('La orientación bloqueada como único arreglo', 'Locked orientation as the only fix')], 0, localized('Conserva el identificador seleccionado y restaura la vista desde ese estado.', 'Keep the selected identifier and restore the view from that state.')),
  quiz('xul-review', 'review', localized('Preparar el cambio para revisión', 'Prepare the change for review'), localized('Has corregido un fallo de navegación. Otra persona debe comprobarlo antes de integrar el cambio. ¿Qué le entregas?', 'You fixed a navigation failure. Someone else must check it before merging the change. What do you hand over?'), [localized('Solo una captura de pantalla', 'Just a screenshot'), localized('Que funcione una vez en mi móvil', 'It worked once on my phone'), localized('Caso reproducible, cambio pequeño y revisión', 'A reproducible case, a small change and a review')], 2, localized('El equipo reproduce el caso y verifica el cambio antes de integrarlo.', 'The team reproduces the case and verifies the change before merging it.')),
  quiz('signlab-coordinates', 'exhibit', localized('Una imagen, muchas zonas', 'One image, many regions'), localized('La imagen del museo se reduce a la mitad. Los puntos táctiles siguen en coordenadas originales. ¿Cómo los alineas?', 'The museum image is scaled down by half. Touch points still use original coordinates. How do you align them?'), [localized('Transformar el toque al sistema de coordenadas de la imagen', 'Transform the touch into image coordinates'), localized('Duplicar todas las zonas a ojo', 'Duplicate every region by eye'), localized('Escalar el tamaño de las zonas sin mover su origen', 'Scale region sizes without moving their origin')], 0, localized('Aplica la transformación inversa de escala y desplazamiento antes de consultar las zonas.', 'Apply the inverse scale and offset transformation before looking up regions.')),
  quiz('signlab-overlap', 'review', localized('Dos salas bajo el mismo dedo', 'Two rooms under one finger'), localized('Dos regiones interactivas se solapan. El visitante recibe dos acciones. ¿Qué falta definir?', 'Two interactive regions overlap. A visitor gets two actions. What must be defined?'), [localized('Un retraso aleatorio', 'A random delay'), localized('Una prioridad determinista y una sola acción por gesto', 'Deterministic priority and one action per gesture'), localized('Desactivar todas las regiones', 'Disable every region')], 1, localized('Una regla de prioridad probada evita respuestas ambiguas en los bordes.', 'A tested priority rule avoids ambiguous responses at boundaries.')),
  quiz('signlab-delivery', 'team', localized('Museo listo para abrir', 'Museum ready to open'), localized('El componente ya responde. ¿Qué conjunto de pruebas representa mejor la visita?', 'The component responds now. Which checks best represent a visit?'), [localized('Solo tocar el centro una vez', 'Only tap the center once'), localized('Solo comprobar que instala', 'Only check installation'), localized('Bordes, escalas y gestos repetidos', 'Boundaries, scales and repeated gestures')], 2, localized('Verifica las interacciones reales, incluidos los casos límite.', 'Verify real interactions, including edge cases.')),
  quiz('school-permissions', 'server', localized('La llave de la sala de servidores', 'The server room key'), localized('Una cuenta de aula no abre una carpeta compartida. La red responde. ¿Qué revisas?', 'A classroom account cannot open a shared folder. The network responds. What do you inspect?'), [localized('Dar administración a todo el alumnado', 'Give every pupil admin rights'), localized('La cuenta, su grupo y los permisos necesarios', 'The account, its group and required permissions'), localized('Quitar la contraseña del servidor', 'Remove the server password')], 1, localized('Comprueba permisos con una cuenta representativa y concede solo lo necesario.', 'Check permissions with a representative account and grant only what is needed.')),
  quiz('school-backup', 'review', localized('Antes de tocar el servidor', 'Before changing the server'), localized('Una actualización requiere reinicio durante las clases. ¿Cómo la preparas?', 'An update requires a reboot during lessons. How do you prepare it?'), [localized('Acordar ventana, verificar copia y planificar recuperación', 'Agree a window, verify the backup and plan recovery'), localized('Reiniciar sin avisar', 'Reboot without notice'), localized('Borrar los registros para liberar espacio', 'Delete logs to free space')], 0, localized('La continuidad de las clases necesita coordinación y una recuperación comprobable.', 'Lesson continuity needs coordination and verifiable recovery.')),
  quiz('school-inventory', 'team', localized('El siguiente turno también cuenta', 'The next shift matters too'), localized('Has recuperado el servicio del aula. ¿Qué dejas al equipo?', 'You restored the classroom service. What do you leave for the team?'), [localized('Nada, ya funciona', 'Nothing, it works now'), localized('La contraseña en la pared', 'The password on the wall'), localized('Síntomas, diagnóstico, cambio y comprobación', 'Symptoms, diagnosis, change and verification')], 2, localized('Documenta la intervención sin exponer credenciales.', 'Document the intervention without exposing credentials.')),
  quiz('alcatel-desk', 'urgent-desk', localized('Una fibra sin destino', 'A fiber without a destination'), localized('El equipo de B-12 detecta que el diseño admite una fibra sin destino. ¿Qué validación debe bloquear la publicación?', 'The B-12 team finds that the design permits a fiber with no destination. Which validation must block publication?'), [localized('Validar que ambos extremos referencian nodos existentes', 'Validate that both ends reference existing nodes'), localized('Ocultar la fibra en el dibujo', 'Hide the fiber in the drawing'), localized('Cambiar el color del cable', 'Change the cable color')], 0, localized('Una conexión necesita extremos válidos; el aspecto del plano no garantiza continuidad.', 'A connection needs valid endpoints; the drawing’s appearance does not guarantee continuity.'), 90),
  quiz('alcatel-statue', 'statue', localized('Calcular el material del tendido', 'Calculate cabling materials'), localized('El diseño validado incluye tramos de distinta longitud y material. ¿Cómo calculas cuánto comprar de cada material?', 'The validated design contains segments of different lengths and materials. How do you calculate how much of each material to buy?'), [localized('Número de tramos por el más largo', 'Segment count times the longest segment'), localized('Sumar longitudes válidas agrupadas por material', 'Sum valid lengths grouped by material'), localized('Usar una longitud media global para cada material', 'Use a global average length for each material')], 1, localized('El presupuesto depende de cantidades y materiales del diseño validado.', 'The estimate depends on quantities and materials in the validated design.')),
  quiz('alcatel-platform', 'review', localized('De herramientas sueltas a plataforma', 'From separate tools to a platform'), localized('Dos herramientas calculan distinto la misma regla de cableado. ¿Cómo reduces la divergencia?', 'Two tools calculate the same cabling rule differently. How do you reduce divergence?'), [localized('Copiar una tercera versión', 'Copy a third version'), localized('Aceptar ambos resultados', 'Accept both results'), localized('Acordar la regla, centralizarla y probar casos comunes', 'Agree the rule, centralize it and test common cases')], 2, localized('Compartir comportamiento de dominio evita que cada interfaz invente su propia regla.', 'Shared domain behavior prevents each interface from inventing its own rule.')),
  quiz('nokia-connectivity', 'server', localized('La fibra que no llega', 'The fiber that goes nowhere'), localized('El plano parece continuo, pero dos extremos no comparten nodo. ¿Qué comprueba la conectividad?', 'The drawing looks continuous, but two endpoints share no node. What checks connectivity?'), [localized('Que las líneas tengan el mismo color', 'That lines have the same color'), localized('Recorrer el grafo de conexiones reales', 'Traverse the graph of actual connections'), localized('Que el dibujo esté centrado', 'That the drawing is centered')], 1, localized('La topología expresa conexiones; la proximidad visual no basta.', 'Topology expresses connections; visual proximity is not enough.')),
  { ...quiz('nokia-snake', 'statue', localized('3310: una ruta indestructible', '3310: an indestructible route'), localized('La estatua del 3310 tiene Snake. Recoge cuatro paquetes sin salirte ni cruzar tu ruta. Puedes jugar por pasos, sin reflejos rápidos.', 'The 3310 statue has Snake. Collect four packets without leaving the board or crossing your route. Play one step at a time; fast reflexes are not needed.'), [localized('Verificar la ruta recogida', 'Verify the collected route'), localized('Dar por conectados todos los nodos', 'Assume every node is connected'), localized('Ignorar las colisiones', 'Ignore collisions')], 0, localized('Ruta completada: el simulador comprueba límites, ocupación y llegada a destino.', 'Route complete: the simulator checks boundaries, occupancy and arrival.')), challenge: 'snake' },
  quiz('nokia-geometry', 'review', localized('Cobertura sin atajos', 'Coverage without shortcuts'), localized('Un tramo cruza el borde de una zona de cobertura. ¿Qué pruebas hacen falta para la intersección?', 'A segment crosses a coverage boundary. Which intersection tests do you need?'), [localized('Cruce, tangencia, extremos y ausencia de cruce', 'Crossing, tangency, endpoints and no crossing'), localized('Solo un tramo horizontal', 'Only one horizontal segment'), localized('Redondear todas las posiciones a cero', 'Round every position to zero')], 0, localized('Los casos geométricos límite evitan validar coberturas incorrectas.', 'Geometric boundary cases prevent incorrect coverage validation.')),
  quiz('vector-report', 'terminal', localized('El informe que se hacía a mano', 'The report that used to be manual'), localized('Automatizas un informe recurrente. ¿Qué demuestra que conserva el significado de los datos?', 'You automate a recurring report. What demonstrates that data meaning is preserved?'), [localized('Más colores en la cabecera', 'More colors in the header'), localized('Comparar casos conocidos y totales con el informe validado', 'Compare known cases and totals with the validated report'), localized('Solo medir lo rápido que termina', 'Only measure how fast it finishes')], 1, localized('Comprueba equivalencia y casos sin datos antes de sustituir el proceso manual.', 'Check equivalence and empty-data cases before replacing the manual process.')),
  quiz('vector-nlp', 'review', localized('Palabras con contexto', 'Words with context'), localized('Un clasificador de sentimiento debe evaluarse. ¿Qué evita medirlo con respuestas que ya ha visto?', 'A sentiment classifier needs evaluation. What avoids measuring it against answers it has already seen?'), [localized('Separar entrenamiento y evaluación antes de ajustar', 'Separate training and evaluation before fitting'), localized('Entrenar y evaluar con los mismos textos', 'Train and evaluate on the same texts'), localized('Eliminar todos los ejemplos difíciles', 'Remove every difficult example')], 0, localized('Reserva datos de evaluación independientes para estimar la generalización.', 'Hold out independent evaluation data to estimate generalization.')),
  quiz('vector-workflow', 'team', localized('Automatización que se puede detener', 'Automation you can stop'), localized('Una campaña automática supera su límite configurado. ¿Qué debería hacer el flujo?', 'An automated campaign exceeds its configured limit. What should the workflow do?'), [localized('Seguir indefinidamente', 'Continue indefinitely'), localized('Ocultar el consumo', 'Hide consumption'), localized('Detener la acción, registrar el motivo y avisar', 'Stop the action, record the reason and notify')], 2, localized('Los límites y la trazabilidad hacen que la automatización sea controlable.', 'Limits and traceability make automation controllable.')),
  quiz('anexia-requirements', 'team', localized('Diez mesas, un producto entero', 'Ten desks, a whole product'), localized('Un cliente pide «gestionar llaves». ¿Qué convierte esa frase en un requisito implementable?', 'A client asks to “manage keys”. What turns that phrase into an implementable requirement?'), [localized('Definir primero el esquema de datos sin validar el flujo', 'Define the data schema before validating the workflow'), localized('Aclarar quién entrega, recibe y registra cada movimiento', 'Clarify who hands over, receives and records each movement'), localized('Crear una tabla sin preguntar', 'Create a table without asking')], 1, localized('Actores, estados y criterios de aceptación guían el diseño de extremo a extremo.', 'Actors, states and acceptance criteria guide end-to-end design.')),
  quiz('anexia-mobile', 'device', localized('Del móvil a producción', 'From mobile to production'), localized('La app Flutter envía dos veces una operación al reconectar. ¿Qué protege la operación en el servidor?', 'The Flutter app sends an operation twice after reconnecting. What protects the operation on the server?'), [localized('Una clave de operación e idempotencia verificada', 'An operation key and verified idempotency'), localized('Deshabilitar el botón solo en la interfaz', 'Disable the button only in the interface'), localized('Añadir un retraso fijo antes de cada reintento', 'Add a fixed delay before each retry')], 0, localized('La interfaz puede reducir dobles toques; el servidor debe controlar reintentos.', 'The interface can reduce double taps; the server must handle retries.')),
  quiz('anexia-valuation', 'review', localized('Una valoración con evidencia', 'A valuation with evidence'), localized('El modelo inmobiliario funciona bien en entrenamiento y mal con viviendas nuevas. ¿Qué investigas?', 'The property model performs well in training and poorly on new homes. What do you investigate?'), [localized('Publicar solo la métrica de entrenamiento', 'Publish only the training metric'), localized('Aumentar los decimales de la predicción', 'Increase decimal places in the prediction'), localized('Sobreajuste, distribución y separación de evaluación', 'Overfitting, distribution and evaluation separation')], 2, localized('La evaluación debe representar los inmuebles sobre los que se va a predecir.', 'Evaluation must represent the properties on which predictions will be made.')),
  quiz('dag-tests', 'review', localized('Feedback antes de la siguiente reunión', 'Feedback before the next meeting'), localized('La suite de integración retrasa cada cambio. ¿Qué mejora su utilidad sin debilitar las pruebas?', 'The integration suite delays every change. What improves usefulness without weakening tests?'), [localized('Borrar las pruebas lentas', 'Delete slow tests'), localized('Aislar dependencias y preparar datos reutilizables', 'Isolate dependencies and prepare reusable test data'), localized('Marcar todos los resultados como correctos', 'Mark every result as passing')], 1, localized('Infraestructura de pruebas y límites claros aceleran feedback conservando comprobaciones.', 'Test infrastructure and clear boundaries speed up feedback while preserving checks.')),
  quiz('dag-ai', 'team', localized('El agente investiga; el equipo decide', 'The agent investigates; the team decides'), localized('Un asistente correlaciona una traza, documentación y código. ¿Qué salida respeta el alcance de diagnóstico?', 'An assistant correlates a trace, documentation and code. Which output respects a diagnostic scope?'), [localized('Informe con evidencia, hipótesis y siguiente comprobación', 'A report with evidence, hypotheses and the next check'), localized('Cambiar producción sin revisión', 'Change production without review'), localized('Presentar una hipótesis como certeza', 'Present a hypothesis as certainty')], 0, localized('El diagnóstico apoya la decisión supervisada del equipo; no autoriza una remediación autónoma.', 'Diagnosis supports the team’s supervised decision; it does not authorize autonomous remediation.')),
];

export interface SideQuest { id: string; chapter: string; target: string; title: LocalizedText; briefing: LocalizedText; options: LocalizedText[]; correct: number; result: LocalizedText; failures: Partial<Record<number, LocalizedText>>; after?: number }
export const sideQuests: SideQuest[] = [
  { id: 'leak', chapter: 'freelance', target: 'sink', title: localized('Una fuga antes de la entrega', 'A leak before delivery'), briefing: localized('Sale agua de la tubería del fregadero y el charco crece. La llave de paso está accesible. ¿Qué haces primero para poder volver al trabajo?', 'Water is leaking from the sink pipe and the puddle is growing. The shutoff valve is accessible. What do you do first so you can get back to work?'), options: [localized('Cerrar la llave y organizar la recogida del agua', 'Close the valve and organize the cleanup'), localized('Recoger el agua sin cerrar la llave', 'Mop up without closing the valve'), localized('Esperar al mantenimiento sin contener la fuga', 'Wait for maintenance without containing the leak')], correct: 0, result: localized('La fuga está contenida y la reparación queda avisada. Puedes retomar la entrega.', 'The leak is contained and a repair has been requested. You can resume delivery.'), failures: { 1: localized('El agua sigue saliendo: tienes que repetir la limpieza.', 'Water keeps flowing: you have to repeat the cleanup.'), 2: localized('El charco se extiende mientras esperas y retrasa la vuelta al trabajo.', 'The puddle spreads while you wait, delaying your return to work.') } },
  { id: 'cat', chapter: 'freelance', target: 'router', title: localized('Sin conexión para enviar la entrega', 'No connection to send the delivery'), briefing: localized('La entrega está lista, pero el router no detecta el cable de red. Ves una marca de mordisco y tienes un cable de repuesto. ¿Qué compruebas primero?', 'The delivery is ready, but the router cannot detect the network cable. You see a bite mark and have a spare cable. What do you check first?'), options: [localized('Reiniciar el servidor de la web', 'Restart the web server'), localized('Apartar al gato, sustituir el cable y verificar el enlace', 'Move the cat away, replace the cable and verify the link'), localized('Cambiar el servidor DNS', 'Change the DNS server')], correct: 1, result: localized('El enlace vuelve y compruebas que la entrega llega a su destino.', 'The link is restored and you verify that the delivery reaches its destination.'), failures: { 0: localized('El reinicio no repara el cable. La entrega sigue sin salir.', 'Restarting does not repair the cable. The delivery still cannot leave.'), 2: localized('Sin enlace físico, el nuevo DNS tampoco responde.', 'Without a physical link, the new DNS server cannot respond either.') } },
  { id: 'foam', chapter: 'freelance', target: 'washer', after: 1, title: localized('La lavadora pierde espuma', 'The washer is leaking foam'), briefing: localized('Han usado jabón de vajilla en la lavadora y sale espuma durante el ciclo. El manual indica detenerlo y seguir el vaciado previsto. ¿Cómo contienes la incidencia?', 'Dish soap was used in the washer and foam is escaping during the cycle. The manual says to stop it and follow the drainage procedure. How do you contain the incident?'), options: [localized('Dejar terminar el ciclo antes de actuar', 'Let the cycle finish before acting'), localized('Abrir la puerta para retirar la espuma', 'Open the door to remove the foam'), localized('Parar el ciclo y coordinar la limpieza siguiendo el manual', 'Stop the cycle and coordinate cleanup following the manual')], correct: 2, result: localized('El ciclo queda detenido y la zona limpia. La incidencia deja de interrumpir el trabajo.', 'The cycle is stopped and the area cleaned. The incident stops interrupting work.'), failures: { 0: localized('El ciclo sigue produciendo espuma y aumenta la limpieza pendiente.', 'The cycle keeps producing foam, increasing the cleanup needed.'), 1: localized('Abrir antes del vaciado deja salir más agua y espuma.', 'Opening before drainage releases more water and foam.') } },
  { id: 'noise', chapter: 'freelance', target: 'team', title: localized('Media hora para revisar la entrega', 'Half an hour to review the delivery'), briefing: localized('Necesitas treinta minutos para revisar la entrega de hoy. El ensayo del salón te impide concentrarte y puede aplazarse. ¿Cómo consigues ese tiempo sin dejar la revisión pendiente?', 'You need thirty minutes to review today’s delivery. Rehearsal in the living room is breaking your concentration and can be rescheduled. How do you make time without leaving the review unfinished?'), options: [localized('Acordar treinta minutos de silencio y retomar después el ensayo', 'Agree on thirty quiet minutes, then resume rehearsal'), localized('Enviar la entrega y revisarla después', 'Send the delivery and review it afterwards'), localized('Esperar a que termine el ensayo sin acordar una hora', 'Wait for rehearsal to end without agreeing on a time')], correct: 0, result: localized('La revisión queda terminada antes del envío y el ensayo tiene un nuevo horario.', 'The review is finished before sending and rehearsal has a new time slot.'), failures: { 1: localized('La entrega sale sin comprobar: toca recuperarla y rehacer la revisión.', 'The delivery goes out unchecked: you must recall it and redo the review.'), 2: localized('Sin una hora acordada, consumes el margen de la entrega esperando.', 'Without an agreed time, you use up the delivery buffer waiting.') } },
  { id: 'xul-lunch', chapter: 'xul', target: 'coffee', title: localized('Un relevo antes de la pausa', 'A handoff before the break'), briefing: localized('Otra persona continuará tu diagnóstico mientras comes. El fallo solo aparece tras girar el móvil. ¿Qué le dejas para que pueda reproducirlo?', 'Someone else will continue your diagnosis during lunch. The failure only appears after rotating the phone. What do you leave so they can reproduce it?'), options: [localized('Una captura del error sin los pasos anteriores', 'An error screenshot without the preceding steps'), localized('Pasos, dispositivo y resultados esperado y observado', 'Steps, device and expected and observed results'), localized('El último registro sin indicar qué sesión falló', 'The latest log without identifying the failed session')], correct: 1, result: localized('El relevo reproduce el fallo y puede continuar el diagnóstico.', 'Your colleague reproduces the failure and can continue the diagnosis.'), failures: { 0: localized('La captura no explica cómo llegar al fallo. El relevo queda bloqueado.', 'The screenshot does not explain how to trigger the failure. The handoff is blocked.'), 2: localized('Sin identificar la sesión, el relevo investiga registros que no corresponden.', 'Without the session identifier, your colleague investigates unrelated logs.') } },
  { id: 'alcatel-coffee', chapter: 'alcatel-lucent', target: 'coffee', title: localized('Guardar el punto del diagnóstico', 'Save your place in the diagnosis'), briefing: localized('Has descartado dos causas del fallo y necesitas una pausa. Al volver debes comprobar los extremos de la fibra. ¿Cómo evitas repetir el trabajo?', 'You have ruled out two causes and need a break. On return, you must check the fiber endpoints. How do you avoid repeating work?'), options: [localized('Guardar solo el mensaje original del error', 'Save only the original error message'), localized('Dejar varias ventanas abiertas sin anotar lo descartado', 'Leave several windows open without recording what was ruled out'), localized('Anotar lo descartado y la siguiente comprobación antes de parar', 'Record what was ruled out and the next check before stopping')], correct: 2, result: localized('Retomas el diagnóstico por los extremos de la fibra, sin repetir las comprobaciones.', 'You resume at the fiber endpoints without repeating checks.'), failures: { 0: localized('El mensaje no conserva tus descartes: repites las dos comprobaciones.', 'The message does not preserve your findings: you repeat both checks.'), 1: localized('Las ventanas no indican qué está comprobado. Pierdes tiempo reconstruyendo el diagnóstico.', 'The windows do not show what was checked. You lose time reconstructing the diagnosis.') } },
  { id: 'family-visit', chapter: 'domingo-alonso', target: 'family', title: localized('Una interrupción en la llamada', 'An interruption during the call'), briefing: localized('Una interrupción familiar requiere un minuto de atención. El equipo espera tu actualización, pero no hay una urgencia en curso. ¿Cómo coordinas la pausa?', 'A family interruption needs a minute of attention. The team is waiting for your update, but there is no active emergency. How do you coordinate the pause?'), options: [localized('Pedir un minuto, atender y retomar con un resumen', 'Ask for a minute, attend to it and resume with a summary'), localized('Apartarte sin avisar al equipo', 'Step away without telling the team'), localized('Seguir dando la actualización mientras atiendes la interrupción', 'Keep giving the update while handling the interruption')], correct: 0, result: localized('El equipo conoce la pausa y recibe una actualización completa al volver.', 'The team knows about the pause and receives a complete update when you return.'), failures: { 1: localized('El equipo sigue esperando sin saber si vas a volver y hay que reorganizar el turno.', 'The team waits without knowing whether you will return and must rearrange speaking turns.'), 2: localized('La actualización queda incompleta y hay que repetirla para acordar el siguiente paso.', 'The update is incomplete and must be repeated to agree on the next step.') } },
];

export const questCopy = {
  fiction: localized('Escenarios y anécdotas recreados con humor. Las misiones son simulaciones; la experiencia profesional está enlazada por separado.', 'Settings and anecdotes recreated with humor. Missions are simulations; professional experience is linked separately.'),
  energy: localized('Energía', 'Energy'), optional: localized('Incidencias opcionales', 'Optional incidents'),
  timer: localized('Contrarreloj', 'Time challenge'), untimed: localized('Sin límite de tiempo', 'No time limit'),
  timeout: localized('Tiempo agotado: −15 energía y reinicio del intento actual. Las misiones completadas se conservan. Reinicia el reloj o continúa sin límite.', 'Time is up: −15 energy and the current attempt resets. Completed missions are preserved. Restart the timer or continue without a limit.'),
  retry: localized('Reiniciar reloj', 'Restart timer'), reach: localized('Ve al objetivo marcado y pulsa E, o usa el acceso directo.', 'Go to the marked objective and press E, or use the shortcut.'),
  route: localized('Misiones de esta etapa', 'Chapter missions'),
  rules: localized('Cada fallo cuesta 15 de energía y, en contrarreloj, 10 segundos. Reinicia la secuencia o ruta actual. Con energía a cero debes descansar antes de continuar.', 'Each mistake costs 15 energy and, in timed mode, 10 seconds. It resets the current sequence or route. At zero energy you must rest before continuing.'),
  penalty: localized('−15 energía (mínimo 0); −10 s en contrarreloj. El intento actual vuelve al principio.', '−15 energy (minimum 0); −10 s in timed mode. The current attempt starts over.'),
  sideRules: localized('Hasta +20 energía si resuelves sin fallos. Si fallas, pierdes 15 de energía, 10 s en contrarreloj y la recompensa de esta incidencia durante la etapa; el intento principal vuelve al principio. La incidencia sigue pendiente.', 'Up to +20 energy if solved without mistakes. A mistake costs 15 energy, 10 s in timed mode and this incident’s reward for the chapter; the main attempt starts over. The incident remains unresolved.'),
  noReward: localized('Recompensa perdida por un fallo anterior: resolver esta incidencia ya no recupera energía.', 'Reward lost due to an earlier mistake: resolving this incident no longer restores energy.'),
  exhausted: localized('Sin energía. Descansa para recuperar 100 de energía y reiniciar el intento actual; conservas las misiones terminadas y las recompensas perdidas.', 'Out of energy. Rest to recover 100 energy and restart the current attempt; completed missions and lost rewards are preserved.'),
  rest: localized('Descansar y reiniciar el intento', 'Rest and restart the attempt'),
  coffee: localized('Pausa en la sala de café: energía al máximo.', 'A break in the coffee room: energy restored to maximum.'),
  infinite: localized('Café gratis e infinito. El 3310 aprueba esta pausa: energía al máximo.', 'Free, unlimited coffee. The 3310 approves this break: energy restored to maximum.'),
  tired: localized('Energía baja: visita la cocina o la sala de café. Al llegar a cero, las respuestas quedan bloqueadas hasta descansar.', 'Low energy: visit the kitchen or coffee room. At zero, answers are blocked until you rest.'),
  focus: localized('Concentración: las distracciones del piso consumen energía. Resolverlas devuelve la calma.', 'Focus: flat distractions consume energy. Resolving them restores calm.'),
  snake: localized('Recoge 4 paquetes. Flechas o botones: un paso cada vez. R reinicia.', 'Collect 4 packets. Arrows or buttons: one step at a time. R restarts.'),
  snakeFail: localized('Colisión. El 3310 sigue entero; reinicia la ruta.', 'Collision. The 3310 is still intact; restart the route.'),
  snakeDone: localized('4 paquetes conectados. Ya puedes verificar la ruta.', '4 packets connected. You can now verify the route.'),
  snakeRestart: localized('Reiniciar Snake', 'Restart Snake'), snakeBoard: localized('Tablero Snake; usa las flechas para moverte', 'Snake board; use arrow keys to move'),
  sideDone: localized('Resuelta', 'Resolved'), shortcut: localized('Acceso directo accesible', 'Accessible shortcut'),
};
