import type { Mission } from './campaign';
import type { LocalizedText } from '../data/professional/types';

const localized = (es: string, en: string): LocalizedText => ({ es, en });
// These are fictional training cases. Career claims continue to come from the public model.
function quiz(id: string, target: string, title: LocalizedText, briefing: LocalizedText, options: LocalizedText[], correct: number, explanation: LocalizedText, seconds = 75): Mission {
  const mechanics: Record<string, Mission['mechanic']> = {
    responsive: 'bug', 'layout-a11y': 'bug', 'xul-lifecycle': 'bug',
    'signlab-coordinates': 'routing', 'signlab-overlap': 'bug', 'signlab-delivery': 'trace',
    'school-permissions': 'trace', 'alcatel-desk': 'bug', 'alcatel-statue': 'routing', 'alcatel-platform': 'architecture',
    'nokia-connectivity': 'trace', 'nokia-snake': 'routing', 'nokia-geometry': 'bug',
    'vector-report': 'trace', 'vector-nlp': 'trace', 'anexia-mobile': 'architecture', 'anexia-valuation': 'trace',
    'dag-tests': 'architecture', 'dag-ai': 'trace',
  };
  return { id, target, seconds, mechanic: mechanics[id] ?? 'priority', title, briefing, choices: options.map((label, i) => ({ id: `${id}-${i}`, label, accepted: i === correct, feedback: i === correct ? explanation : localized(`Revisa el requisito. ${explanation.es}`, `Check the requirement. ${explanation.en}`) })) };
}

export const extraMissions: Mission[] = [
  quiz('responsive', 'terminal', localized('Maquetación contra reloj', 'Layout against the clock'), localized('El cliente revisa la web en un móvil de 360 px. La columna fija de 960 px desborda. ¿Qué cambio probarías?', 'The client reviews the site on a 360 px phone. A fixed 960 px column overflows. What would you test?'), [localized('Ocultar todo el desbordamiento', 'Hide all overflow'), localized('width: 100%; max-width: 960px y revisar el contenido', 'width: 100%; max-width: 960px and check the content'), localized('Reducir todo el texto a 8 px', 'Shrink all text to 8 px')], 1, localized('El contenedor se adapta. Comprueba también imágenes, espaciado y navegación en móvil.', 'The container adapts. Also check images, spacing and navigation on mobile.'), 45),
  quiz('layout-a11y', 'review', localized('La entrega también se usa con teclado', 'Delivery works with a keyboard too'), localized('El menú solo se abre al pasar el ratón. ¿Cómo permites acceder sin ratón?', 'The menu only opens on hover. How do you make it usable without a mouse?'), [localized('Botón real, foco visible y estado expandido', 'A real button, visible focus and expanded state'), localized('Un div con un icono más grande', 'A div with a larger icon'), localized('Explicar que hace falta un ratón', 'Explain that a mouse is required')], 0, localized('La interacción debe poder operarse con teclado y comunicar su estado.', 'The interaction must work with a keyboard and communicate its state.')),
  quiz('client-handoff', 'team', localized('Cerrar alcance, abrir la puerta', 'Close scope, open the door'), localized('La web está lista. Llega un «ya que estamos» con cinco páginas nuevas. ¿Cómo cierras la entrega?', 'The site is ready. A “while you are at it” request adds five pages. How do you close delivery?'), [localized('Añadirlo todo sin cambiar la fecha', 'Add everything without changing the date'), localized('Ignorar el mensaje', 'Ignore the message'), localized('Validar lo acordado y presupuestar la ampliación', 'Validate the agreed scope and estimate the extension')], 2, localized('Una entrega verificable y un alcance explícito protegen al cliente y al proyecto.', 'Verifiable delivery and explicit scope protect the client and the project.')),
  quiz('xul-learn', 'team', localized('Luz al fondo de la cueva', 'Light at the back of the cave'), localized('La oficina es preciosa; el equipo programa al fondo. No conoces el componente Android que debes cambiar. ¿Por dónde empiezas?', 'The office is lovely; the developers work at the back. You do not know the Android component you must change. Where do you start?'), [localized('Reescribirlo de memoria', 'Rewrite it from memory'), localized('Reproducir el caso y pedir una revisión guiada', 'Reproduce the case and ask for a guided review'), localized('Cambiar varias cosas hasta que compile', 'Change several things until it builds')], 1, localized('Un ejemplo mínimo y una revisión convierten la tarea en aprendizaje compartido.', 'A minimal example and a review turn the task into shared learning.')),
  quiz('xul-lifecycle', 'terminal', localized('El museo gira', 'The museum rotates'), localized('Al girar el móvil, la ficha seleccionada vuelve a la primera. ¿Qué hay que conservar?', 'Rotating the phone resets the selected exhibit to the first one. What should survive?'), [localized('La selección como estado restaurable', 'The selection as restorable state'), localized('Una referencia permanente a la pantalla destruida', 'A permanent reference to the destroyed screen'), localized('La orientación bloqueada como único arreglo', 'Locked orientation as the only fix')], 0, localized('Conserva el identificador seleccionado y restaura la vista desde ese estado.', 'Keep the selected identifier and restore the view from that state.')),
  quiz('xul-review', 'review', localized('La revisión del compañero esqueleto', 'The skeleton colleague’s review'), localized('Hoy un esqueleto de utilería ocupa una silla; las demás son pelotas. Antes de ir a la cocina, ¿qué deja lista tu tarea?', 'A prop skeleton occupies a chair today; the other seats are exercise balls. Before heading to the kitchen, what makes your task ready?'), [localized('Solo una captura de pantalla', 'Just a screenshot'), localized('Que funcione una vez en mi móvil', 'It worked once on my phone'), localized('Caso reproducible, cambio pequeño y revisión', 'A reproducible case, a small change and a review')], 2, localized('El humor se queda en el decorado; el comportamiento se comprueba con el equipo.', 'The humor stays in the scenery; behavior is checked with the team.')),
  quiz('signlab-coordinates', 'exhibit', localized('Una imagen, muchas zonas', 'One image, many regions'), localized('La imagen del museo se reduce a la mitad. Los puntos táctiles siguen en coordenadas originales. ¿Cómo los alineas?', 'The museum image is scaled down by half. Touch points still use original coordinates. How do you align them?'), [localized('Transformar el toque al sistema de coordenadas de la imagen', 'Transform the touch into image coordinates'), localized('Duplicar todas las zonas a ojo', 'Duplicate every region by eye'), localized('Aumentar el volumen del móvil', 'Increase the phone volume')], 0, localized('Aplica la transformación inversa de escala y desplazamiento antes de consultar las zonas.', 'Apply the inverse scale and offset transformation before looking up regions.')),
  quiz('signlab-overlap', 'review', localized('Dos salas bajo el mismo dedo', 'Two rooms under one finger'), localized('Dos regiones interactivas se solapan. El visitante recibe dos acciones. ¿Qué falta definir?', 'Two interactive regions overlap. A visitor gets two actions. What must be defined?'), [localized('Un retraso aleatorio', 'A random delay'), localized('Una prioridad determinista y una sola acción por gesto', 'Deterministic priority and one action per gesture'), localized('Desactivar todas las regiones', 'Disable every region')], 1, localized('Una regla de prioridad probada evita respuestas ambiguas en los bordes.', 'A tested priority rule avoids ambiguous responses at boundaries.')),
  quiz('signlab-delivery', 'team', localized('Museo listo para abrir', 'Museum ready to open'), localized('El componente ya responde. ¿Qué conjunto de pruebas representa mejor la visita?', 'The component responds now. Which checks best represent a visit?'), [localized('Solo tocar el centro una vez', 'Only tap the center once'), localized('Solo comprobar que instala', 'Only check installation'), localized('Bordes, escalas y gestos repetidos', 'Boundaries, scales and repeated gestures')], 2, localized('Verifica las interacciones reales, incluidos los casos límite.', 'Verify real interactions, including edge cases.')),
  quiz('school-permissions', 'server', localized('La llave de la sala de servidores', 'The server room key'), localized('Una cuenta de aula no abre una carpeta compartida. La red responde. ¿Qué revisas?', 'A classroom account cannot open a shared folder. The network responds. What do you inspect?'), [localized('Dar administración a todo el alumnado', 'Give every pupil admin rights'), localized('La cuenta, su grupo y los permisos necesarios', 'The account, its group and required permissions'), localized('Quitar la contraseña del servidor', 'Remove the server password')], 1, localized('Comprueba permisos con una cuenta representativa y concede solo lo necesario.', 'Check permissions with a representative account and grant only what is needed.')),
  quiz('school-backup', 'review', localized('Antes de tocar el servidor', 'Before changing the server'), localized('Una actualización requiere reinicio durante las clases. ¿Cómo la preparas?', 'An update requires a reboot during lessons. How do you prepare it?'), [localized('Acordar ventana, verificar copia y planificar recuperación', 'Agree a window, verify the backup and plan recovery'), localized('Reiniciar sin avisar', 'Reboot without notice'), localized('Borrar los registros para liberar espacio', 'Delete logs to free space')], 0, localized('La continuidad de las clases necesita coordinación y una recuperación comprobable.', 'Lesson continuity needs coordination and verifiable recovery.')),
  quiz('school-inventory', 'team', localized('El siguiente turno también cuenta', 'The next shift matters too'), localized('Has recuperado el servicio del aula. ¿Qué dejas al equipo?', 'You restored the classroom service. What do you leave for the team?'), [localized('Nada, ya funciona', 'Nothing, it works now'), localized('La contraseña en la pared', 'The password on the wall'), localized('Síntomas, diagnóstico, cambio y comprobación', 'Symptoms, diagnosis, change and verification')], 2, localized('Documenta la intervención sin exponer credenciales.', 'Document the intervention without exposing credentials.')),
  quiz('alcatel-desk', 'urgent-desk', localized('¿Dónde estaba mi mesa?', 'Where was my desk?'), localized('Urgente: encuentra el puesto B-12 entre las mesas. El plano ya te ha llevado hasta aquí. El diseño admite una fibra sin destino. ¿Qué impide publicarlo?', 'Urgent: find desk B-12 among the desks. The map has brought you here. The design permits a fiber with no destination. What prevents publication?'), [localized('Validar que ambos extremos referencian nodos existentes', 'Validate that both ends reference existing nodes'), localized('Ocultar la fibra en el dibujo', 'Hide the fiber in the drawing'), localized('Cambiar el color del cable', 'Change the cable color')], 0, localized('Una conexión necesita extremos válidos; el aspecto del plano no garantiza continuidad.', 'A connection needs valid endpoints; the drawing’s appearance does not guarantee continuity.'), 90),
  quiz('alcatel-statue', 'statue', localized('El One Touch Easy de la feria', 'The fairground One Touch Easy'), localized('Un One Touch Easy verde gigante ilumina el vestíbulo. En el simulador, cada tramo puede tener longitud distinta. ¿Cómo calculas el material?', 'A giant green One Touch Easy lights up the lobby. In the simulator, each segment may have a different length. How do you calculate materials?'), [localized('Número de tramos por el más largo', 'Segment count times the longest segment'), localized('Sumar longitudes válidas agrupadas por material', 'Sum valid lengths grouped by material'), localized('Contar las bombillas de la estatua', 'Count the statue’s light bulbs')], 1, localized('El presupuesto depende de cantidades y materiales del diseño validado.', 'The estimate depends on quantities and materials in the validated design.')),
  quiz('alcatel-platform', 'review', localized('De herramientas sueltas a plataforma', 'From separate tools to a platform'), localized('Dos herramientas calculan distinto la misma regla de cableado. ¿Cómo reduces la divergencia?', 'Two tools calculate the same cabling rule differently. How do you reduce divergence?'), [localized('Copiar una tercera versión', 'Copy a third version'), localized('Aceptar ambos resultados', 'Accept both results'), localized('Acordar la regla, centralizarla y probar casos comunes', 'Agree the rule, centralize it and test common cases')], 2, localized('Compartir comportamiento de dominio evita que cada interfaz invente su propia regla.', 'Shared domain behavior prevents each interface from inventing its own rule.')),
  quiz('nokia-connectivity', 'server', localized('La fibra que no llega', 'The fiber that goes nowhere'), localized('El plano parece continuo, pero dos extremos no comparten nodo. ¿Qué comprueba la conectividad?', 'The drawing looks continuous, but two endpoints share no node. What checks connectivity?'), [localized('Que las líneas tengan el mismo color', 'That lines have the same color'), localized('Recorrer el grafo de conexiones reales', 'Traverse the graph of actual connections'), localized('Que el dibujo esté centrado', 'That the drawing is centered')], 1, localized('La topología expresa conexiones; la proximidad visual no basta.', 'Topology expresses connections; visual proximity is not enough.')),
  { ...quiz('nokia-snake', 'statue', localized('3310: una ruta indestructible', '3310: an indestructible route'), localized('La estatua del 3310 tiene Snake. Recoge cuatro paquetes sin salirte ni cruzar tu ruta. Puedes jugar por pasos, sin reflejos rápidos.', 'The 3310 statue has Snake. Collect four packets without leaving the board or crossing your route. Play one step at a time; fast reflexes are not needed.'), [localized('Verificar la ruta recogida', 'Verify the collected route'), localized('Dar por conectados todos los nodos', 'Assume every node is connected'), localized('Ignorar las colisiones', 'Ignore collisions')], 0, localized('Ruta completada: el simulador comprueba límites, ocupación y llegada a destino.', 'Route complete: the simulator checks boundaries, occupancy and arrival.')), challenge: 'snake' },
  quiz('nokia-geometry', 'review', localized('Cobertura sin atajos', 'Coverage without shortcuts'), localized('Un tramo cruza el borde de una zona de cobertura. ¿Qué pruebas hacen falta para la intersección?', 'A segment crosses a coverage boundary. Which intersection tests do you need?'), [localized('Cruce, tangencia, extremos y ausencia de cruce', 'Crossing, tangency, endpoints and no crossing'), localized('Solo un tramo horizontal', 'Only one horizontal segment'), localized('Redondear todas las posiciones a cero', 'Round every position to zero')], 0, localized('Los casos geométricos límite evitan validar coberturas incorrectas.', 'Geometric boundary cases prevent incorrect coverage validation.')),
  quiz('vector-report', 'terminal', localized('El informe que se hacía a mano', 'The report that used to be manual'), localized('Automatizas un informe recurrente. ¿Qué demuestra que conserva el significado de los datos?', 'You automate a recurring report. What demonstrates that data meaning is preserved?'), [localized('Más colores en la cabecera', 'More colors in the header'), localized('Comparar casos conocidos y totales con el informe validado', 'Compare known cases and totals with the validated report'), localized('Solo medir lo rápido que termina', 'Only measure how fast it finishes')], 1, localized('Comprueba equivalencia y casos sin datos antes de sustituir el proceso manual.', 'Check equivalence and empty-data cases before replacing the manual process.')),
  quiz('vector-nlp', 'review', localized('Palabras con contexto', 'Words with context'), localized('Un clasificador de sentimiento debe evaluarse. ¿Qué evita medirlo con respuestas que ya ha visto?', 'A sentiment classifier needs evaluation. What avoids measuring it against answers it has already seen?'), [localized('Separar entrenamiento y evaluación antes de ajustar', 'Separate training and evaluation before fitting'), localized('Entrenar y evaluar con los mismos textos', 'Train and evaluate on the same texts'), localized('Eliminar todos los ejemplos difíciles', 'Remove every difficult example')], 0, localized('Reserva datos de evaluación independientes para estimar la generalización.', 'Hold out independent evaluation data to estimate generalization.')),
  quiz('vector-workflow', 'team', localized('Automatización que se puede detener', 'Automation you can stop'), localized('Una campaña automática supera su límite configurado. ¿Qué debería hacer el flujo?', 'An automated campaign exceeds its configured limit. What should the workflow do?'), [localized('Seguir indefinidamente', 'Continue indefinitely'), localized('Ocultar el consumo', 'Hide consumption'), localized('Detener la acción, registrar el motivo y avisar', 'Stop the action, record the reason and notify')], 2, localized('Los límites y la trazabilidad hacen que la automatización sea controlable.', 'Limits and traceability make automation controllable.')),
  quiz('anexia-requirements', 'team', localized('Diez mesas, un producto entero', 'Ten desks, a whole product'), localized('Un cliente pide «gestionar llaves». ¿Qué convierte esa frase en un requisito implementable?', 'A client asks to “manage keys”. What turns that phrase into an implementable requirement?'), [localized('Diseñar primero un icono naranja', 'Design an orange icon first'), localized('Aclarar quién entrega, recibe y registra cada movimiento', 'Clarify who hands over, receives and records each movement'), localized('Crear una tabla sin preguntar', 'Create a table without asking')], 1, localized('Actores, estados y criterios de aceptación guían el diseño de extremo a extremo.', 'Actors, states and acceptance criteria guide end-to-end design.')),
  quiz('anexia-mobile', 'device', localized('Del móvil a producción', 'From mobile to production'), localized('La app Flutter envía dos veces una operación al reconectar. ¿Qué protege la operación en el servidor?', 'The Flutter app sends an operation twice after reconnecting. What protects the operation on the server?'), [localized('Una clave de operación e idempotencia verificada', 'An operation key and verified idempotency'), localized('Cambiar el color del botón', 'Change the button color'), localized('Suponer que la red nunca falla', 'Assume the network never fails')], 0, localized('La interfaz puede reducir dobles toques; el servidor debe controlar reintentos.', 'The interface can reduce double taps; the server must handle retries.')),
  quiz('anexia-valuation', 'review', localized('Una valoración con evidencia', 'A valuation with evidence'), localized('El modelo inmobiliario funciona bien en entrenamiento y mal con viviendas nuevas. ¿Qué investigas?', 'The property model performs well in training and poorly on new homes. What do you investigate?'), [localized('Publicar solo la métrica de entrenamiento', 'Publish only the training metric'), localized('Inventar más precisión decimal', 'Invent more decimal precision'), localized('Sobreajuste, distribución y separación de evaluación', 'Overfitting, distribution and evaluation separation')], 2, localized('La evaluación debe representar los inmuebles sobre los que se va a predecir.', 'Evaluation must represent the properties on which predictions will be made.')),
  quiz('dag-tests', 'review', localized('Feedback antes de la siguiente reunión', 'Feedback before the next meeting'), localized('La suite de integración retrasa cada cambio. ¿Qué mejora su utilidad sin debilitar las pruebas?', 'The integration suite delays every change. What improves usefulness without weakening tests?'), [localized('Borrar las pruebas lentas', 'Delete slow tests'), localized('Aislar dependencias y preparar datos reutilizables', 'Isolate dependencies and prepare reusable test data'), localized('Marcar todos los resultados como correctos', 'Mark every result as passing')], 1, localized('Infraestructura de pruebas y límites claros aceleran feedback conservando comprobaciones.', 'Test infrastructure and clear boundaries speed up feedback while preserving checks.')),
  quiz('dag-ai', 'team', localized('El agente investiga; el equipo decide', 'The agent investigates; the team decides'), localized('Un asistente correlaciona una traza, documentación y código. ¿Qué salida respeta el alcance de diagnóstico?', 'An assistant correlates a trace, documentation and code. Which output respects a diagnostic scope?'), [localized('Informe con evidencia, hipótesis y siguiente comprobación', 'A report with evidence, hypotheses and the next check'), localized('Cambiar producción sin revisión', 'Change production without review'), localized('Presentar una hipótesis como certeza', 'Present a hypothesis as certainty')], 0, localized('El diagnóstico apoya la decisión supervisada del equipo; no autoriza una remediación autónoma.', 'Diagnosis supports the team’s supervised decision; it does not authorize autonomous remediation.')),
];

export interface SideQuest { id: string; chapter: string; target: string; title: LocalizedText; briefing: LocalizedText; options: LocalizedText[]; correct: number; result: LocalizedText; after?: number }
export const sideQuests: SideQuest[] = [
  { id: 'leak', chapter: 'freelance', target: 'sink', title: localized('El agua no espera al deploy', 'Water will not wait for deployment'), briefing: localized('Una fuga invade la cocina del piso alquilado. El compañero médico pasa en calzoncillos, capa y con un fuet: «¡Yo cubro la retirada!»', 'A leak reaches the rented flat’s kitchen. The doctor flatmate walks past in underpants and a cape, eating fuet: “I will cover the retreat!”'), options: [localized('Cerrar la llave y organizar la recogida del agua', 'Close the valve and organize the cleanup'), localized('Seguir maquetando mientras sube el agua', 'Keep laying out the page as the water rises'), localized('Poner el portátil en el suelo', 'Put the laptop on the floor')], correct: 0, result: localized('Agua contenida. El héroe de la capa trae las toallas. Recuperas 20 de energía.', 'Water contained. The caped hero brings towels. Recover 20 energy.') },
  { id: 'cat', chapter: 'freelance', target: 'router', title: localized('El gato se ha comido Internet', 'The cat ate the Internet'), briefing: localized('El router ha perdido el enlace: el gato mordisquea el cable. El cuarto compañero del piso está de guardia en la cocina.', 'The router has lost its link: the cat is chewing the cable. The fourth flatmate is on kitchen duty.'), options: [localized('Reiniciar la web veinte veces', 'Restart the website twenty times'), localized('Atraer al gato con su juguete, apartarlo y sustituir el cable', 'Lure the cat away with its toy and replace the cable'), localized('Culpar al DNS sin comprobar el enlace', 'Blame DNS without checking the link')], correct: 1, result: localized('Gato a salvo, cable protegido y enlace verificado. Internet vuelve. +20 energía.', 'Cat safe, cable protected and link verified. Internet is back. +20 energy.') },
  { id: 'foam', chapter: 'freelance', target: 'washer', after: 1, title: localized('Fairy no es detergente de lavadora', 'Dish soap is not laundry detergent'), briefing: localized('Alguien ha confundido Fairy con detergente de lavadora. La espuma conquista el pasillo. El compañero bajito entra en su baile de «la bilirrubina».', 'Someone confused Fairy dish soap with laundry detergent. Foam takes over the hall. The short flatmate launches into his “bilirubin” dance.'), options: [localized('Añadir más jabón', 'Add more soap'), localized('Abrir la puerta en pleno ciclo', 'Open the door mid-cycle'), localized('Parar el ciclo y coordinar la limpieza siguiendo el manual', 'Stop the cycle and coordinate cleanup following the manual')], correct: 2, result: localized('La espuma retrocede; el baile se muda al salón. +20 energía.', 'The foam retreats; the dance moves to the living room. +20 energy.') },
  { id: 'noise', chapter: 'freelance', target: 'team', title: localized('Trompeta, guitarra y una nube misteriosa', 'Trumpet, guitar and a mysterious cloud'), briefing: localized('El opositor de coronilla despejada ensaya dos instrumentos. Una nube discreta flota sobre el sofá. Hay una entrega pendiente.', 'The balding exam candidate rehearses two instruments. A discreet cloud floats above the sofa. A delivery is due.'), options: [localized('Acordar un rato de silencio y turnos para ensayar', 'Agree on quiet time and rehearsal slots'), localized('Competir subiendo la música', 'Compete by turning up the music'), localized('Prometer trabajar sin dormir', 'Promise to work without sleeping')], correct: 0, result: localized('El grupo respeta el bloque de concentración. +20 energía.', 'The group respects the focus block. +20 energy.') },
  { id: 'xul-lunch', chapter: 'xul', target: 'coffee', title: localized('Se cocina algo más que código', 'More than code is cooking'), briefing: localized('La cocina prepara comida. Antes de comer, otra persona necesita entender tu bug. ¿Qué le dejas?', 'Lunch is cooking. Before eating, someone else needs to understand your bug. What do you leave them?'), options: [localized('Un «no funciona» sin contexto', '“It does not work” with no context'), localized('Pasos para reproducirlo y el resultado esperado', 'Reproduction steps and the expected result'), localized('Cincuenta capturas sin ordenar', 'Fifty unsorted screenshots')], correct: 1, result: localized('Traspaso claro y comida caliente. +20 energía.', 'Clear handoff and a hot meal. +20 energy.') },
  { id: 'alcatel-coffee', chapter: 'alcatel-lucent', target: 'coffee', title: localized('El comedor de las mil mesas', 'The thousand-table cafeteria'), briefing: localized('Has encontrado la máquina de café al otro lado de la oficina. ¿Qué haces antes de retomar la urgencia?', 'You found the coffee machine across the office. What do you do before returning to the urgent task?'), options: [localized('Cambiar de tarea sin apuntar nada', 'Switch tasks without recording anything'), localized('Abrir tres urgencias más', 'Open three more urgent tasks'), localized('Anotar la siguiente comprobación y hacer una pausa', 'Note the next check and take a break')], correct: 2, result: localized('Pausa hecha. Vuelves con contexto y 20 de energía.', 'Break taken. Return with context and 20 energy.') },
  { id: 'family-visit', chapter: 'domingo-alonso', target: 'family', title: localized('Se cuela una pequeña compañera', 'A little colleague drops in'), briefing: localized('Trabajas desde casa. Marga está cerca y la peque aparece en la videollamada con un dibujo. El equipo espera una actualización.', 'You work from home. Marga is nearby and your little one joins the video call with a drawing. The team is waiting for an update.'), options: [localized('Pedir un minuto, atenderla y retomar con un resumen', 'Ask for a minute, give her attention and resume with a summary'), localized('Prometer estar en dos sitios a la vez', 'Promise to be in two places at once'), localized('Cambiar producción mientras miras el dibujo', 'Change production while looking at the drawing')], correct: 0, result: localized('Dibujo en la pared y expectativas claras. +20 energía. La familia también forma parte del viaje.', 'Drawing on the wall and clear expectations. +20 energy. Family is part of the journey too.') },
];

export const questCopy = {
  fiction: localized('Escenarios y anécdotas recreados con humor. Las misiones son simulaciones; la experiencia profesional está enlazada por separado.', 'Settings and anecdotes recreated with humor. Missions are simulations; professional experience is linked separately.'),
  energy: localized('Energía', 'Energy'), optional: localized('Incidencias opcionales', 'Optional incidents'),
  timer: localized('Contrarreloj', 'Time challenge'), untimed: localized('Sin límite de tiempo', 'No time limit'),
  timeout: localized('Tiempo agotado. Puedes reintentar o continuar sin límite; conservas lo que has resuelto.', 'Time is up. Retry or continue without a limit; your solved steps are preserved.'),
  retry: localized('Reiniciar reloj', 'Restart timer'), reach: localized('Ve al objetivo marcado y pulsa E, o usa el acceso directo.', 'Go to the marked objective and press E, or use the shortcut.'),
  route: localized('Misiones de esta etapa', 'Chapter missions'), sideRetry: localized('Esa opción no resuelve la incidencia. Prueba otra.', 'That option does not resolve the incident. Try another.'),
  coffee: localized('Pausa en la sala de café: energía al máximo.', 'A break in the coffee room: energy restored to maximum.'),
  infinite: localized('Café gratis e infinito. El 3310 aprueba esta pausa: energía al máximo.', 'Free, unlimited coffee. The 3310 approves this break: energy restored to maximum.'),
  tired: localized('Energía baja: visita la cocina o la sala de café. Puedes seguir jugando.', 'Low energy: visit the kitchen or coffee room. You can keep playing.'),
  focus: localized('Concentración: las distracciones del piso consumen energía. Resolverlas devuelve la calma.', 'Focus: flat distractions consume energy. Resolving them restores calm.'),
  snake: localized('Recoge 4 paquetes. Flechas o botones: un paso cada vez. R reinicia.', 'Collect 4 packets. Arrows or buttons: one step at a time. R restarts.'),
  snakeFail: localized('Colisión. El 3310 sigue entero; reinicia la ruta.', 'Collision. The 3310 is still intact; restart the route.'),
  snakeDone: localized('4 paquetes conectados. Ya puedes verificar la ruta.', '4 packets connected. You can now verify the route.'),
  snakeRestart: localized('Reiniciar Snake', 'Restart Snake'), snakeBoard: localized('Tablero Snake; usa las flechas para moverte', 'Snake board; use arrow keys to move'),
  sideDone: localized('Resuelta', 'Resolved'), shortcut: localized('Acceso directo accesible', 'Accessible shortcut'),
};
