import type { ComponentChildren } from 'preact';
import { useLocale } from '../i18n/context';
import { getPlatform934, type PlatformStatus } from '../data/platform934';
import { ProjectGallery, ProjectLinks } from './ProjectMedia';
import type { UiData } from '../data/ui';

const statusLabel = (status: PlatformStatus, es: boolean) => ({ VALIDATED: es ? 'VALIDADO' : 'VALIDATED', IMPLEMENTED: es ? 'IMPLEMENTADO' : 'IMPLEMENTED', IN_PROGRESS: es ? 'EN DESARROLLO' : 'IN PROGRESS', PLANNED: es ? 'PLANIFICADO' : 'PLANNED', HISTORICAL: es ? 'HISTÓRICO' : 'HISTORICAL' }[status]);
function Status({ value }: { value: PlatformStatus }) { const { locale } = useLocale(); return <span class="platform-status">{statusLabel(value, locale === 'es')}</span>; }
function Section({ id, title, children }: { id?: string; title: string; children: ComponentChildren }) { return <section id={id} class="platform-section"><h2>{title}</h2>{children}</section>; }
function List({ items }: { items: string[] }) { return <ul class="platform-list">{items.map(item => <li key={item}>{item}</li>)}</ul>; }

export default function Platform934({ data }: { data: UiData }) {
  const { locale, href } = useLocale(); const p = getPlatform934(locale); const es = locale === 'es';
  const project = data.portfolio.projects.find(project => project.id === 'platform934')!;
  const l = (spanish: string, english: string) => es ? spanish : english;
  return <article class="platform934" data-platform934>
    <a class="back-link" href={href('/projects/')}>← {l('Todos los proyectos', 'All projects')}</a>
    <header class="platform-hero"><p class="eyebrow">{p.eyebrow}</p><img class="project-logo" src={project.logo!.src} width={project.logo!.width} height={project.logo!.height} alt="" /><h1>{p.title}</h1><p class="lead">{project.description}</p><div class="tags">{p.technologies.map(technology => <span key={technology}>{technology}</span>)}</div></header>
    <ProjectGallery images={project.images} />
    <p class="project-status"><strong>{project.status}</strong></p><ProjectLinks project={project} />
    <Section id="overview" title={project.challengeTitle}><p>{project.challenge}</p></Section>
    <Section id="clients" title={l('Ecosistema multicliente', 'Multi-client ecosystem')}><div class="platform-client-grid">{p.clients.map(client => <article class="platform-card" key={client.id}><div class="platform-card-heading"><h3>{client.name}</h3><Status value={client.status} /></div><p>{client.description}</p><dl><dt>{l('Propósito', 'Purpose')}</dt><dd>{client.purpose}</dd><dt>{l('Tecnología', 'Technology')}</dt><dd>{client.technology}</dd></dl>{client.id === 'tv-web' && <p class="platform-annotation">TV WEB CLIENT · {l('cliente real', 'real client')}</p>}</article>)}</div></Section>
    <Section id="landscape" title={l('Paisaje del sistema', 'System landscape')}><figure class="platform-diagram" aria-labelledby="platform-diagram-title" aria-describedby="platform-diagram-description"><h3 id="platform-diagram-title">{l('Clientes Platform934 y capas de producto', 'Platform934 clients and product layers')}</h3><figcaption id="platform-diagram-description">{l('Los clientes pueden comunicarse directamente con Jellyfin para operaciones normales. Platform934 API es una capa opcional para capacidades de agente y producto.', 'Clients may communicate directly with Jellyfin for ordinary operations. Platform934 API is an optional layer for agent and product capabilities.')}</figcaption><div class="platform-flow"><div class="platform-node platform-node-wide"><strong>{l('Clientes Platform934', 'Platform934 clients')}</strong><span>{l('Móvil · Web · TV Web / Preact · Google TV nativo · Flutter TV de referencia', 'Mobile · Web · TV Web / Preact · Native Google TV · Flutter TV reference')}</span></div><div class="platform-arrows" aria-hidden="true">↓ | ↘</div><div class="platform-flow-split"><div class="platform-node"><strong>Jellyfin</strong><span>{l('Catálogo y reproducción multimedia', 'Catalogue and media playback')}</span></div><div class="platform-node"><strong>Platform934 API</strong><span>{l('Capa opcional de agente y producto', 'Optional agent and product layer')}</span></div></div><div class="platform-arrows" aria-hidden="true">↓</div><div class="platform-node platform-node-agent"><strong>Platform934 Agent</strong><span>Semantic Kernel → LiteLLM → LLM provider(s)</span><small>{l('Herramientas: cliente Jellyfin tipado → API oficial de Jellyfin', 'Tools: typed Jellyfin client → official Jellyfin API')}</small></div></div></figure></Section>
    <Section id="boundary" title={l('Límite Jellyfin / Platform934', 'Jellyfin / Platform934 boundary')}><div class="platform-boundary"><article><h3>Jellyfin</h3><List items={p.boundary.jellyfin} /></article><article><h3>Platform934</h3><List items={p.boundary.platform} /></article></div><p class="muted">{l('Platform934 no construye el servidor, el transcodificador ni el pipeline de codecs de Jellyfin.', 'Platform934 does not build Jellyfin’s server, transcoder or codec pipeline.')}</p></Section>
    <Section id="evolution" title={l('Evolución de clientes', 'Client evolution')}><div class="platform-timeline">{p.evolution.map((item, index) => <article key={item.title}><span class="timeline-index">0{index + 1}</span><div><h3>{item.title}</h3><Status value={item.status!} /><p>{item.body}</p></div></article>)}</div></Section>
    <Section id="native-tv" title={l('Deep dive: Google TV nativo', 'Deep dive: native Google TV')}><p>{l('La especialización nativa se concentra donde el comportamiento de TV exige control más profundo, sin afirmar que todas las funciones estén igual de completas.', 'Native specialization focuses where TV behaviour requires deeper control, without implying that every feature is equally complete.')}</p><div class="platform-detail-grid">{p.native.map(item => <article key={item.title}><h3>{item.title}</h3><Status value={item.status!} /><p>{item.body}</p></article>)}</div></Section>
    <Section id="playback" title={l('Playback / Media3', 'Playback / Media3')}><p>{l('Media3 concentra la propiedad del reproductor y la sesión nativa, la continuidad, la recuperación y la interacción con audio/subtítulos. La validación se mantiene acotada a escenarios, corpus y dispositivos.', 'Media3 owns the native player and session, continuity, recovery and audio/subtitle interaction. Validation remains bounded by scenarios, media corpus and devices.')}</p></Section>
    <Section id="performance" title={l('Ingeniería de rendimiento', 'Performance engineering')}><p class="platform-context">{l('Medido en hardware TV real en un escenario de validación controlado. Son resultados acotados, no garantías universales.', 'Measured on real TV hardware in a controlled validation scenario. These are scoped results, not universal guarantees.')}</p><div class="platform-metrics">{p.performance.map(item => <article key={item.title}><h3>{item.title}</h3><strong>{item.body}</strong></article>)}</div><p class="muted">{l('El trabajo de rendimiento es iterativo; la deuda restante se conserva explícitamente en lugar de ocultarla.', 'Performance work is iterative; remaining debt is retained explicitly rather than hidden.')}</p></Section>
    <Section id="api" title={l('Platform934 API', 'Platform934 API')}><p>{l('Backend .NET independiente y privado, una puerta de enlace externa de agentes por encima de Jellyfin. Las operaciones normales de cliente pueden seguir yendo directamente a Jellyfin.', 'An independent, private .NET backend and external agent gateway layered over Jellyfin. Ordinary client operations may still go directly to Jellyfin.')}</p><div class="platform-api-grid">{p.api.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div><div class="tags"><span>.NET</span><span>Semantic Kernel</span><span>LiteLLM</span><span>typed contracts</span><span>allowlisted tools</span></div></Section>
    <Section id="agent" title={l('Agente conversacional', 'Conversational agent')}><p>{l('Un agente conversacional con acceso acotado a capacidades reales de Platform934/Jellyfin. No es un agente autónomo.', 'A conversational agent with bounded access to real Platform934/Jellyfin capabilities. It is not autonomous.')}</p><div class="platform-capabilities">{p.agent.map(item => <article key={item.title}><span>{item.title}</span><Status value={item.status!} /></article>)}</div><p>{l('El grounding puede trabajar con catálogo, detalles, historial, favoritos y señales visto/no visto disponibles. MCP no está implementado.', 'Grounding can work with available catalogue, details, history, favourites and watched/unwatched signals. MCP is not implemented.')}</p></Section>
    <Section id="product-ai" title={l('IA de producto', 'Product AI')}><p>{l('Capacidades para quien usa Platform934: descubrimiento conversacional, recomendaciones, listas, discusión y explicación de películas y acciones de producto mediante herramientas acotadas.', 'Capabilities for Platform934 users: conversational discovery, recommendations, lists, film discussion and explanation, and bounded tool-based product actions.')}</p></Section>
    <Section id="agentic-engineering" title={l('Agentic Engineering', 'Agentic Engineering')}><p>{l('Cómo se construye Platform934, separado de la IA runtime del producto:', 'How Platform934 is built, separate from runtime product AI:')}</p><ol class="platform-workflow">{p.workflow.map((item, index) => <li key={item}><span>0{index + 1}</span>{item}</li>)}</ol><p class="platform-callout">{l('Delegar implementación no significa delegar el juicio técnico.', 'Delegating implementation does not mean delegating technical judgement.')}</p></Section>
    <Section id="decisions" title={l('Decisiones y trade-offs', 'Decisions and trade-offs')}><div class="platform-decision-grid">{p.decisions.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></Section>
    <Section id="learnings" title={l('Aprendizajes', 'Learnings')}><ol class="platform-learnings">{p.learnings.map((item, index) => <li key={item}><span>0{index + 1}</span>{item}</li>)}</ol></Section>
    <Section id="status" title={l('Estado actual', 'Current status')}><div class="platform-status-grid"><article><Status value="VALIDATED" /><p>{l('Slices nativos, fundamentos Media3 y métricas de rendimiento acotadas.', 'Native slices, Media3 foundations and scoped performance measurements.')}</p></article><article><Status value="IMPLEMENTED" /><p>{l('Superficies multicliente, API backend y capacidades conversacionales aprobadas.', 'Multi-client surfaces, API backend and approved conversational capabilities.')}</p></article><article><Status value="IN_PROGRESS" /><p>{l('Hardening nativo, migración progresiva y orquestación remota más amplia.', 'Native hardening, progressive migration and broader remote orchestration.')}</p></article><article><Status value="HISTORICAL" /><p>{l('Rutas de cliente anteriores conservadas como referencia o rollback.', 'Earlier client paths retained as reference or rollback.')}</p></article></div></Section>
    <Section id="relations" title={l('Proyectos conectados', 'Connected projects')}><div class="actions">{project.relations.map(relation => <a class="button" key={relation.target} href={href(`/projects/${relation.target}/`)}>{data.portfolio.projects.find(item => item.id === relation.target)?.name} →</a>)}</div></Section>
  </article>;
}
