name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "The TOKEN is:$TOKEN"
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /
          customArgs: --dart-define="GITHUB_TOKEN=$TOKEN"