name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The TOKEN is:$G_TOKEN"
      - run: echo "The TOKEN is:${{env.G_TOKEN}}"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /
          customArgs: --dart-define="G_TOKEN=${{env.G_TOKEN}}"